---@class UnityEngine.SystemLanguage : System.Enum
---@field public Afrikaans UnityEngine.SystemLanguage @static
---@field public Arabic UnityEngine.SystemLanguage @static
---@field public Basque UnityEngine.SystemLanguage @static
---@field public Belarusian UnityEngine.SystemLanguage @static
---@field public Bulgarian UnityEngine.SystemLanguage @static
---@field public Catalan UnityEngine.SystemLanguage @static
---@field public Chinese UnityEngine.SystemLanguage @static
---@field public Czech UnityEngine.SystemLanguage @static
---@field public Danish UnityEngine.SystemLanguage @static
---@field public Dutch UnityEngine.SystemLanguage @static
---@field public English UnityEngine.SystemLanguage @static
---@field public Estonian UnityEngine.SystemLanguage @static
---@field public Faroese UnityEngine.SystemLanguage @static
---@field public Finnish UnityEngine.SystemLanguage @static
---@field public French UnityEngine.SystemLanguage @static
---@field public German UnityEngine.SystemLanguage @static
---@field public Greek UnityEngine.SystemLanguage @static
---@field public Hebrew UnityEngine.SystemLanguage @static
---@field public Hugarian UnityEngine.SystemLanguage @static
---@field public Icelandic UnityEngine.SystemLanguage @static
---@field public Indonesian UnityEngine.SystemLanguage @static
---@field public Italian UnityEngine.SystemLanguage @static
---@field public Japanese UnityEngine.SystemLanguage @static
---@field public Korean UnityEngine.SystemLanguage @static
---@field public Latvian UnityEngine.SystemLanguage @static
---@field public Lithuanian UnityEngine.SystemLanguage @static
---@field public Norwegian UnityEngine.SystemLanguage @static
---@field public Polish UnityEngine.SystemLanguage @static
---@field public Portuguese UnityEngine.SystemLanguage @static
---@field public Romanian UnityEngine.SystemLanguage @static
---@field public Russian UnityEngine.SystemLanguage @static
---@field public SerboCroatian UnityEngine.SystemLanguage @static
---@field public Slovak UnityEngine.SystemLanguage @static
---@field public Slovenian UnityEngine.SystemLanguage @static
---@field public Spanish UnityEngine.SystemLanguage @static
---@field public Swedish UnityEngine.SystemLanguage @static
---@field public Thai UnityEngine.SystemLanguage @static
---@field public Turkish UnityEngine.SystemLanguage @static
---@field public Ukrainian UnityEngine.SystemLanguage @static
---@field public Vietnamese UnityEngine.SystemLanguage @static
---@field public ChineseSimplified UnityEngine.SystemLanguage @static
---@field public ChineseTraditional UnityEngine.SystemLanguage @static
---@field public Unknown UnityEngine.SystemLanguage @static
---@field public Hungarian UnityEngine.SystemLanguage @static
---@field public value__ number
local m = {}

UnityEngine.SystemLanguage = m
return m
